#!/bin/bash

FILES='system/application/controllers'

cd ../http
TESTDATE=`date +"%m-%d-%y"`
OUTDIR="tests/$TESTDATE"

mkdir -p $OUTDIR

echo 'Generating test outputs'


#CONTROLLERS="admin auth calendar docs forum grouppage groups home mail pages pm search test upload userpage users"
CONTROLLERS=""
for file in `ls $FILES`; 
do
	CONTROLLERS="$CONTROLLERS `echo $file | sed -n '/[a-Z^\.]*\.php/p' | sed 's/\([a-Z]*\)\.php/\1/'`"
done


rm $OUTDIR/all.html
for cont in $CONTROLLERS; do
	#if [[ "$cont" == "userpage" ]]; then
	#	echo " Processing controller $cont..."
	#else
		echo " Processing controller $cont..."
		php index.php $cont test > $OUTDIR/$cont.html
		cat $OUTDIR/$cont.html >> $OUTDIR/all.html
	#fi
done

PASSED=`grep Passed $OUTDIR/all.html | wc -l`
FAILED=`grep Failed $OUTDIR/all.html | wc -l`

echo "Passed: $PASSED <br />" > $OUTDIR/results.html
echo "Failed: $FAILED" >> $OUTDIR/results.html

#create coverage reports
REPORTS=phpcoverage/reports/$TESTDATE
mkdir -p $REPORTS
cd $REPORTS
for cont in $CONTROLLERS; do
	rm $cont-report -rf
	#if [[ "$cont" == "userpage" ]]; then
	#	echo " Processing controller $cont..."
	#elif [[ "$cont" == "test" ]]; then
	if [[ "$cont" == "test" ]]; then
		#test controller, which can't have a test() func. Has 'allModels' instead
		php ../../bin/all.php $cont allModels
	else
		php ../../bin/all.php $cont test
	fi
	mv report $cont-report
done
